import Head from "next/head";
import styles from "@/styles/Games.module.css";
import NavigationBar from "@/components/NavigationBar/NavigationBarComponent";
import { useUser } from "@/contexts/userContext";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import useFetchBackendData from "@/hooks/fetchBackendData";
import IGamePost from "@/interfaces/IGamePost";
import GamePost from "@/components/GamePost/GamePostComponent";

export default function Games() {
  const { userToken } = useUser();
  const { getGamesFeed } = useFetchBackendData();
  const router = useRouter();
  const [gamesFeed, setGamesFeed] = useState<IGamePost[] | undefined>(undefined)

  useEffect(() => {
    (userToken == null || userToken == undefined) && router.push("/");
  }, [userToken, router]);

  useEffect(() => {
    const getGamesPosts = async (token: string) => {
      const listOfPosts: any = await getGamesFeed(token);
      listOfPosts != undefined && setGamesFeed(listOfPosts);
    }
    (gamesFeed == null || gamesFeed == undefined) && userToken != undefined && getGamesPosts(userToken);
  }, [getGamesFeed, gamesFeed]);

  return (
    <>
      <Head>
        <title>Home - Bettek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavigationBar />
        <div className={styles.gamePostContainer}>
          {gamesFeed != undefined && gamesFeed != null && gamesFeed.length > 0 ?
            gamesFeed.map((game: IGamePost) => {
                return (
                    <GamePost game={game} key={game.id} />
                )
        })
            : <p>No feed founded</p>}
        </div>
      </main>
    </>
  );
}
