import Head from "next/head";
import styles from "@/styles/Home.module.css";
import IUserPost from "@/interfaces/IUserPost";
import UserPost from "@/components/UserPost/UserPostComponent";
import NavigationBar from "@/components/NavigationBar/NavigationBarComponent";
import { useUser } from "@/contexts/userContext";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import useFetchBackendData from "@/hooks/fetchBackendData";

export default function Home() {
  const { userToken } = useUser();
  const { getPostFeed } = useFetchBackendData();
  const router = useRouter();
  const [usersPosts, setUsersPosts] = useState<IUserPost[] | undefined>(undefined)

  useEffect(() => {
    (userToken == null || userToken == undefined) && router.push("/");
  }, [userToken, router]);

  useEffect(() => {
    const getUsersPosts = async () => {
      const listOfPosts: any = await getPostFeed();
      console.log("list of post:", listOfPosts?.data);
      listOfPosts != undefined && listOfPosts != null && listOfPosts.data != null && setUsersPosts(listOfPosts.data);
    }
    (usersPosts == null || usersPosts == undefined) && getUsersPosts();
  }, [getPostFeed, usersPosts]);

  return (
    <>
      <Head>
        <title>Home - Bettek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavigationBar />
        <div className={styles.userPostContainer}>
          {usersPosts != undefined && usersPosts != null && usersPosts.length > 0 ?
            usersPosts.map((post: IUserPost) => {
            return (
              <UserPost post={post} key={post.id} />
            )})
            : null}
        </div>
      </main>
    </>
  );
}
